name: "bluebell"
mode: "debug"
port: 8080
version: "v0.0.1"
start_time: "2020-07-01"
machine_id: 1

auth:
  jwt_expire: 8760

log:
  level: "info"
  dir: "log"
  filename: "web_app.log"
  fotmat: "console" # "json"
  is_write: true
  max_size: 200
  max_age: 30
  max_backups: 7

mysql:
  host: "127.0.0.1"
  port: 3306
  user: "demo"
  password: "qaz123"
  dbname: "test"
  max_open_conns: 200
  max_idle_conns: 50

redis:
  host: "127.0.0.1"
  port: 6379
  password: "qaz123"
  db: 0
  pool_size: 100