// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"cloud-disk/core/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/user/login",
				Handler: UserLoginHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/user/details",
				Handler: UserDetailsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/mail/send",
				Handler: MailCodeSendHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/register",
				Handler: UserRegisterHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/user/share/info",
				Handler: UserShareBasicInfoHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/file/upload",
					Handler: FileUploadHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/user/repository/save",
					Handler: UserRepositorySaveHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/user/file/list",
					Handler: UserFileListHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/user/file/update",
					Handler: UserFileUpdateHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/user/folder/create",
					Handler: UserFolderCreateHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/user/file/delete",
					Handler: UserFileDeleteHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/user/file/move",
					Handler: UserFileMoveHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/user/share/create",
					Handler: UserShareBasicCreateHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/user/share/save",
					Handler: UserShareBasicSaveHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/user/refresh/token",
					Handler: UserRefreshTokenHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/user/file/secondupload",
					Handler: UserFileSecondUploadHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/user/file/upload/prepare",
					Handler: UserFileUploadPrepareHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/user/file/chunk/upload",
					Handler: UserFileChunkUploadHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/user/file/upload/chunk/complete",
					Handler: UserFileUploadChunkCompleteHandler(serverCtx),
				},
			}...,
		),
	)
}
