# 系统配置
system:
  env: release
  host: 0.0.0.0
  addr: 8080
  name: app-server
  db-type: mysql
  oss-type: local

# 日志配置项
logger:
  level: 'debug'                         # 日志级别: debug, info, warn, error, dpanic, panic, fatal, 默认 info
  format: 'console'                     # 输出格式: console, json
  prefix: '[gvb-blog] '                 # 日志前缀
  director: 'log'                       # 存放日志的文件夹
  show-line: true                       # 是否显示哪行调用
  encode-level: 'LowercaseLevelEncoder' # LowercaseColorLevelEncoder
  stacktrace-key: 'app'                 # 栈名
  log-in-console: true                  # 是否输出到控制台
  maxsize: 5                            # 日志文件最大的尺寸(M), 超限后开始自动分割
  maxbackups: 10                        # 保留旧文件的最大个数
  maxage: 7                             # 保留旧文件的最大天数
  compress: true                        # 是否壓縮

# mysql数据库配置
mysql:
  host: 10.0.0.91
  port: "3306"
  config: charset=utf8mb4&parseTime=True&loc=Local
  db-name: gvb-blog
  username: root
  password: "123456"
  max-idle-conns: 0
  max-open-conns: 0
  log-mode: "info" # 日志级别 silent, error, warn, info, 默认 info; silent 相当于关闭日志
  log-level: dev
  log-zap: false
  table-prefix: "gvb_"

# jwt 认证与授权 配置
jwt:
  buffer-time: 86400
  expires-time: 604800
  issuer: the7s
  signing-key: d6888d35-75a4-44e5-bc9d-a3ba327bb586