mysql:
  host: 10.0.0.91
  port: "3306"
  db: gvb-blog
  username: root
  password: "123456"
  config: charset=utf8mb4&parseTime=True&loc=Local
  max-idle-conns: 0
  max-open-conns: 0
  log_mode: ""
system:
  host: 0.0.0.0
  port: 8080
  env: release
  version: "1.0"
logger:
  level: debug
  format: console
  prefix: '[gvb-blog] '
  director: log
  showLine: false
  encode-level: LowercaseLevelEncoder
  stacktrace-key: app
  log-in-console: true
  maxsize: 5
  maxbackups: 10
  maxage: 7
  compress: true
elastic:
  host: 127.0.0.1
  port: "9200"
  username: admin
  password: "123456"
  set_gizp: false
  set_sniff: false
  health_check_tiame: 10
  set_errorlog: 'ES-ERROR '
  set_infolog: 'ES-INFO '
site_info:
  created_at: "2023-04-10"
  bei_an: 粤ICP备2021010654号-3
  title: 个人博客
  qq_image: http://www.fengfengzhidao.com/static/my/img/footer/qq.png
  version: "1.1"
  email: hu729919300@163.com
  wechat_image: http://www.fengfengzhidao.com/static/my/img/footer/wechat.png
  name: hu417
  job: 运维开发
  addr: 广东深圳
  slogan: hu417个人博客
  slogan_en: hu417blog
  web: http://wwv.baidu.com/
  bilibiliurl: https://www.bilibili.com/
  gitee_url: https://gitee.com
  github_url: https://github.com
