// Code generated by goctl. DO NOT EDIT.
package types

type LoginRequest struct {
	Name     string `json:"name"`
	Password string `json:"password"`
}

type LoginResponse struct {
	Token        string `json:"token"`
	RefreshToken string `json:"refresh_token"`
}

type UserDetailsReq struct {
	Identity string `json:"identity"`
}

type UserDetailsResp struct {
	Name  string `json:"name"`
	Email string `json:"email"`
}

type MailCodeReq struct {
	Email string `json:"email"`
}

type MailCodeResp struct {
	Msg  string `json:"msg"`
	Code string `json:"code"`
}

type UserRegisterReq struct {
	Name     string `json:"name"`
	Password string `json:"password"`
	Email    string `json:"email"`
	Code     string `json:"code"`
}

type UserRegisterResp struct {
	Name     string `json:"name"`
	Password string `json:"password"`
	Email    string `json:"email"`
	Code     string `json:"code"`
}

type FileUploadReq struct {
	Hash string `json:"hash,optional"`
	Name string `json:"name,optional"`
	Ext  string `json:"ext,optional"`
	Size int    `json:"size,optional"`
	Path string `json:"path,optional"`
}

type FileUploadResp struct {
	Identity string `json:"identity"`
	Ext      string `json:"ext"`
	Name     string `json:"name"`
}

type UserRepositorySaveReq struct {
	ParentId           int    `json:"parentid" description:"父级id"`
	RepositoryIdentity string `json:"repositoryIdentity"`
	Ext                string `json:"ext"`
	Name               string `json:"name"`
}

type UserRepositorySaveResp struct {
	Identity string `json:"identity"`
}

type UserFileListReq struct {
	Id   int `json:"id,optional"`
	Page int `json:"page,optional" description:"页数"`
	Size int `json:"size,optional" description:"每页条数"`
}

type UserFileListResp struct {
	List  []*UserFile `json:"list,optional"`
	Count int64       `json:"count,optional"`
}

type UserFile struct {
	Id                 int    `json:"id"`
	Identity           string `json:"identity"`
	RepositoryIdentity string `json:"repository_identity"`
	Name               string `json:"name"`
	Ext                string `json:"ext"`
	Path               string `json:"path"`
	Size               string `json:"size"`
}

type UserFileUpdateReq struct {
	Identity string `json:"identity"`
	Name     string `json:"name"`
}

type UserFileUpdateResp struct {
	Identity string `json:"identity"`
	Name     string `json:"name"`
}

type UserFolderCreateReq struct {
	ParentId int    `json:"parent_id"`
	Name     string `json:"name"`
}

type UserFolderCreateResp struct {
	Identity string `json:"identity"`
	Name     string `json:"name"`
}

type UserFileDeleteReq struct {
	Identity string `json:"identity"`
}

type UserFileDeleteResp struct {
	Message string `json:"message"`
}

type UserFileMoveReq struct {
	Identity       string `json:"identity"`
	ParentIdentity int    `json:"parent_identity"`
}

type UserFileMoveResp struct {
	Message string `json:"message"`
}

type UserShareBasicCreateReq struct {
	UserRepositoryIdentity string `json:"user_repository_identity"`
	Expiredtime            int    `json:"expired_time"`
}

type UserShareBasicCreateResp struct {
	Identity string `json:"identity"`
}

type UserShareBasicInfoReq struct {
	Identity string `json:"identity"`
}

type UserShareBasicInfoResp struct {
	RepositoryIdentity string `json:"repository_identity"`
	Name               string `json:"name"`
	Ext                string `json:"ext"`
	Size               int    `json:"size"`
	Path               string `json:"path"`
}

type UserShareBasicSaveReq struct {
	RepositoryIdentity string `json:"repository_identity"`
	ParentId           int    `json:"parent_id"`
}

type UserShareBasicSaveResp struct {
	Identity string `json:"identity"`
}

type UserRefreshTokenReq struct {
}

type UserRefreshTokenResp struct {
	Token        string `json:"token"`
	RefreshToken string `json:"refresh_token"`
	Message      string `json:"message"`
}

type UserFileSecondUploadReq struct {
	Md5  string `json:"md5"`
	Name string `json:"name"`
}

type UserFileSecondUploadResp struct {
	Identity string `json:"identity"`
	UploadId string `json:"uploadId"`
}

type UserFileUploadPrepareReq struct {
	Md5  string `json:"md5"`
	Name string `json:"name"`
	Ext  string `json:"ext"`
}

type UserFileUploadPrepareResp struct {
	Identity string `json:"identity"`
	UploadId string `json:"upload_id"`
	Key      string `json:"key"`
}

type UserFileChunkUploadReq struct {
}

type UserFileChunkUploadResp struct {
	Etag string `json:"etag" description:"获取分片文件chunk的md5值"`
}

type UserFileUploadChunkCompleteReq struct {
	Key        string       `json:"key"`
	UploadId   string       `json:"upload_id"`
	CosObjects []CosObjects `json:"cos_objects"`
}

type CosObjects struct {
	PartNumber int    `json:"part_number"`
	Etag       string `json:"etag"`
}

type UserFileUploadChunkCompleteResp struct {
}
